#global variables
teams_city = []
teams_abb = []
mylist1 = []
mylist2 = []
sports_teams_dict = {}

GAME_ID = []
TEAM_ID = []
GAME_DATE_EST = []
TEAM_ABBREVIATION = []
TEAM_CITY_NAME = []
TEAM_WINS_LOSSES = []
PTS_QTR1 = []
PTS_QTR2 = []
PTS_QTR3 = []
PTS_QTR4 = []
PTS = []
FG_PCT = []
FT_PCT = []
FG3_PCT = []
AST = []
REB = []
TOV = []